// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALYqCH5-_drdBtjupLheaHSlXM7oUCsFs',
    appId: '1:697599783110:web:6b024b359a123dbfeae7c7',
    messagingSenderId: '697599783110',
    projectId: 'epsilonflutter',
    authDomain: 'epsilonflutter.firebaseapp.com',
    storageBucket: 'epsilonflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWmH6ktzNcDqjJKMsU-Lxj_2ydSIj78w',
    appId: '1:697599783110:android:f0f46d5656c1542feae7c7',
    messagingSenderId: '697599783110',
    projectId: 'epsilonflutter',
    storageBucket: 'epsilonflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNxQev6vi0rWZb26ZFyl2rW0L7rnHrmpI',
    appId: '1:697599783110:ios:14c62747ffe43c3aeae7c7',
    messagingSenderId: '697599783110',
    projectId: 'epsilonflutter',
    storageBucket: 'epsilonflutter.firebasestorage.app',
    iosBundleId: 'com.example.epsilon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNxQev6vi0rWZb26ZFyl2rW0L7rnHrmpI',
    appId: '1:697599783110:ios:14c62747ffe43c3aeae7c7',
    messagingSenderId: '697599783110',
    projectId: 'epsilonflutter',
    storageBucket: 'epsilonflutter.firebasestorage.app',
    iosBundleId: 'com.example.epsilon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALYqCH5-_drdBtjupLheaHSlXM7oUCsFs',
    appId: '1:697599783110:web:47a033d910771911eae7c7',
    messagingSenderId: '697599783110',
    projectId: 'epsilonflutter',
    authDomain: 'epsilonflutter.firebaseapp.com',
    storageBucket: 'epsilonflutter.firebasestorage.app',
  );
}
